### ISSUE TITLE
root user cannot login with password

### ISSUE THREAD

**Issue by StephenKing** [TYPO3-infrastructure/virtinstaller#3]
As long as the SSH keys are not in place, we could bootstrap with password. However, ssh does not allow password login.

**Comment by pniederlag** [comment]
ssh does allow password login, at least last time I tried it. But only until chef has bootstrapped the node of course, as "our" chef will disable root login.

But, ssh-login from outside does not work on tcp/ip-level when the machine in attached to br-int only.

I'll investigate wether knife bootstrap --ssh-gateway would solve this and report back here. https://docs.chef.io/knife_bootstrap.html

**Comment by StephenKing** [comment]
Sorry, me idiot did not follow the readme. Then it worked.
Regarding the `--ssh-gateway`: Once we're connected via VPN, it shouldn't be a problem anyway.
I could just imagine to create the `/root/.ssh` dir at the end of the preseed file and move the copy-in of the key file into `virt-installer-debian`.

**Comment by pniederlag** [comment]
ok, so you did not run 'virt-copy-in -d $DOMAIN authorized_keys /root/.ssh/' ? Well, then you at least can't login via ssh-key. So I would like to change my statement from the last comment, actually I didn't try the password login but used the key-login. So you are probably right that root-login via password is NOT enabled by default. ;)

If we could automate the step to add the public ssh-keys into the machine it would be awesome. Not sure wether preseeding does offer a solution to this. virt-copy-in unfortunatly does only work when the domain is in shutdown state. ;(

**Comment by StephenKing** [comment]
Yes, we don't need password login :-)

My idea would be to include in the script:

* use preseed `late_command` to create `/root/.ssh` (optionally: download keys from somwhere :-)). I found this example: `d-i preseed/late_command string apt-install zsh; in-target chsh -s /bin/zsh`
* shut down the VM after `virt-install`
* run `virt-copy-in`
* start VM

**Comment by StephenKing** [comment]
fixed by including all of that into the script
